apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: devquotes
    namespace: devquotes
    labels:
        app: devquotes
    annotations:
        kubernetes.io/ingress.class: nginx
spec:
    tls:
        - hosts:
            - ENC[AES256_GCM,data:afytnMR2A7EP8qd32Y3BDl4qCRZ9SbcnEzw=,iv:MVmwcsgQPIruIioRWXSsfEwgFT8Fk73OkgzERRwDboQ=,tag:9B17n9z15bypXzI5+acRjQ==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:JFkz7S93My6JDvzetN5cWtPE8amxzkscpt0=,iv:nvJSIqnjD6jrgyhDGHf3geL4VwCxn7sBqcAy1lC2B1E=,tag:DICbRrmZiLSjkYY1JbbkaA==,type:str]
          http:
            paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                        name: devquotes
                        port:
                            number: 8080
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T22:38:23Z"
    mac: ENC[AES256_GCM,data:Y9BEDqAu2Oc97OelErLUxHxZLaqoiHpUtjxQc9zGyh3Qs08bBX9zpMQvYILSgnT14xAZXQhfXIRFyc53ZS2OGKChYTCGKqmx1ULhgRy+mkkGB+Qw9/mowUSOEqs+yvNYX8+WgvS60umK3QqBorCBQ26mD/DzVxRZ42vc70YCAT8=,iv:KnrWMYHFda8pd0Rd+KroV4rgwlGuPIrxFQffHCrFQv4=,tag:nSDh2+wkzZnFl8WtAAiJew==,type:str]
    pgp:
        - created_at: "2021-05-05T22:38:23Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwP8FxNnerN5AQ/9GmYmkuLQrkr2lT3Kn43mjfNTK/IChOVdO1E2zQT2I13m
            uvU2p4zPbZzpheekBYn7AgUdrUboozLhvRhgtAPJ8TtDO/dG7H7ZH9XRvcADvRRb
            mPNm8nVAdTmH/YFaQVzeIeXy5GgpT8tOrzPfG+1hqOMNF0MJkoyV5zddOEf9g17o
            aIzG8C0E1j8+tumgFGOwYLLA1MWp0Ht0hTNHXMUUoQ9AUp/0y3LtyboiGrr/6CcI
            S18GQNGkEZwAitnDuDahoLVholZQiwILtOWFC88wwCC2oPU7b5KWiCKzK9IhFuki
            u1tFsl7rM9+8W6rtehGIWc3nVp+F6+lta79vaPepgJ8LSKsBjLuo3HIqDthoMXeX
            JW+46/YrPTvhZJz839vs0NE6ZtTcrVLEVaLWwmPTrqPbEdUpCqI0oL7Qmedov9gP
            tJ5jiFgaQsXi3nmXw6Wrd1zMoQdvNdN0rmhBeXGetfiIAs5EWs/CAjQp9AmOmvXt
            KGEGGTLj06LtrjNEjAHnX6GkNah9tkDDGdrvmn2GM2MiuX+NVEjmddzcYabIqIn5
            9c7NwIJG1ahdnhp7OjRR7PFQpOjyoJVv0gttVGoDgAwX0DZAcCUknDOaXWLthae3
            WKyk05SwucYU6Ts4nZWXXsruuMn77axgq52To5+sivD2iz4GJ7ENseSxRkOZd5bS
            TgEwlkYT+RS8l/tVmg475L9hPWOQ9qD91z50pHnyY1aruVptKL5qVixiswEwmNPG
            kFOvXdNPG415c8yYdMmhth8PuR1S6HRk2+P54aWZIQ==
            =Eer0
            -----END PGP MESSAGE-----
          fp: FEE43962AC34E28FB078EFA9F6C9CFE02626638C
    encrypted_regex: ^(data|stringData|host|hosts)$
    version: 3.7.1
